### PR TITLE
Add the ability to change the password encrypting a secret key

### LINKED ISSUE #75: Change password protecting secret key
As the secret key is encrypted with a key derived from a password, can this be changed retrospectively to a new password?

If not, can the secret key scalar value be exfiltrated and used to generate the same pub/priv pair with a new password?

### LINKED ISSUE #99: #75 is still open technically
https://github.com/jedisct1/minisign/issues/75 ‒ I actually have (or at least had; it forced me to change my key once) the same issue… OP in there, after closing the issue, asked if he should submit a PR, however, no response came (presumably because there are no notifications on comments on closed issues?)… So this issue's just a reminder, and a possible continuation of the original one, I guess…

### PR DESCRIPTION
**Pull request by winterqt**
This closes #75 and closes #99.

The only thing I can't figure out how to do is update the man page, since I couldn't find what source file is fed into Ronn.
Other than that, this should be good to go (if there aren't any glaring issues with the implementation).

### CODE REVIEW

**Comment by jedisct1** [comment]
Thanks a lot! I'm going to take a look at it as soon as I have access to an actual computer.

The source of the man page is the `manage.md` file.

**Comment by winterqt** [comment]
> The source of the man page is the `manpage.md` file.

Thanks! Not sure how I missed that. 😅

I've pushed an updated manpage; let me know if there are any issues with wording, etc.

**Comment by winterqt** [comment]
Hey @jedisct1, do you mind reviewing this when you get a chance? (Just poking you since it's been 2 weeks.)

**Comment by winterqt** [comment]
@jedisct1 Do you mind taking a look at this?

**Comment by winterqt** [comment]
@jedisct1 Poke :)

**Comment by kzshantonu** [comment]
+1 Poke

**Comment by winterqt** [comment]
@jedisct1 I have to admit, it's a bit disheartening to not get a response for over a year, but then you closing my PR without any communication other than that you wrote a superior implementation. Thank you for implementing the feature, but this does make me somewhat wary to contribute to projects of yours in the future.

**Comment by jedisct1** [comment]
Don't take it personally. I'm having a really hard time understanding foreign code.

And when it is sensitive code, I fear I would merge code I don't fully understand and introduce vulnerabilities, or have code that I won't be able to maintain in the future.

**Pull request closed without merging**
