### PR TITLE
refactor: Move business logic away from cli logic

### PR DESCRIPTION
**Pull request by kallisti5**
* This allows static linkage of minisign into C applications without dragging along the main() + cli
* More cleanup is needed, but this splits the business logic into seperate files vs a bunch of static functions.

### CODE REVIEW

**Comment by kallisti5** [comment]
oh.. future changes would involve cleaning up the names of these functions to be less generic and prone to collision.
   ex:  minisign_verify vs "verify"

I didn't want to get too far down in the weeds though without checking in here via a PR first :-)

**Comment by jedisct1** [comment]
A minisign library would be better as a distinct project, especially if the intent is to only do verification.

Adding the ability to build a library to [minizign](https://github.com/jedisct1/zig-minisign) would be trivial. It's small, simple and self-contained (doesn't need libsodium).

Unfortunately, Haiku is only a tier-3 platform for Zig.

**Comment by jedisct1** [comment]
The CLI is not meant to return errors to applications, nor to free memory before exiting, so that's another reason for a dedicated library.

**Comment by jedisct1** [comment]
Here's what a more serious approach could look like: https://github.com/jedisct1/minisign-verify-c/

(completely untested, probably doesn't work)

**Comment by kallisti5** [comment]
Oh.. ok. That works too :laughing: 
I went ahead and just integrated this code into our Package kit after some style cleanup.

I made sure to maintain your copyright inline with our design (and maintain the MIT licensing aspect). Please let me know if it's ok with you.
https://review.haiku-os.org/c/haiku/+/6361

**Pull request closed without merging**
